### ISSUE TITLE
Does not work with Atmega88

### ISSUE THREAD

**Issue by andrebrait** [raphnet/gc_n64_usb#1]
First of all, thanks a lot!!! I managed to get the circuit working with the Atmega8 like a charm. However, I had the unfortunate opportunity to confirm it does mot work with the Atmega88 because the seller who sold me the Atmega8 also sent an Atmega88 by mistake. 

I have tried fuses and hex from both the Atmega8 and 168. All i can get is something between an unknown device and an input device with an yellow bang on it. I know it's not supposed to work on the 88, but I thought confirming it does not would be good, so here I am.

Thanks again!

**Comment by andrebrait** [comment]
It just ocurred to me that I may have to compile it myself for the 88 instead of using the 168 hex file. I'll try it tomorrow.

**Comment by raphnet** [comment]
I can confirm an Atmega88-specific build is necessary. In case it helps, I just pushed a Makefile for Atmega88. It compiles but I have not tested on real hardware. According to the datasheets, the ATmega168 fuse are correct for the Atmega88 too. Please let me know how it goes. 

Oh, and I can upload an atmega88 hexfile too if it helps. Let me know.

**Comment by andrebrait** [comment]
Thank you, Raphael!

I've tried compiling it to the Atmega88 but I have found out that I have a Atmega88PA-PU, which needs a different build (target must be atmega88p IIRC). I'll build it this afternoon and I'll tell you if I succeeded. 

Thanks a lot for the Makefile! It seems I may have to alter a thing or two for the Atmega88p in the project itself as it seems V-USB has trouble building against it.

**Comment by andrebrait** [comment]
@raphnet I can't find the makefile for the atmega88. Maybe there was a problem with the push?

**Comment by raphnet** [comment]
@andrebrait Ah, right. I pushed to my internal server instead of github. Fixed this just now.

**Comment by andrebrait** [comment]
It works!!!

I just had to change the target! The Fuses for the Atmega168 work for the Atmega88P, as expected. However, avrdude 6.3 won't set efuse to 0x01, complaining it should be 0x9F instead. Using an older version works well.

Just replace every occurrence of 88 with 88p in your makefile for the Atmega88 and you have a Makefile for the Atmega88p!

**Comment by raphnet** [comment]
Are you sure changing the target was necessary? The atmega88 and Atmega88p targets yield an identical hex file (same md5 sum) for me.

But when it comes to flashing the file, I can imagine avrdude complains that the chip ID does not match... I'll add a makefile as you suggest. Thanks!

**Comment by andrebrait** [comment]
Well, what changes between the 168 and the 88 makefile? Before I tried the 88 makefile with the target changed to the 88p, I had tried modifying the 168 by replacong every instance of 168 to 88 and changing the avrdude target to 88p and that didn't work when I flashed it (I had read that I wasn't supposed to compile V-USB to any of the P-variants and that I should compilr using the regular variant as target and then flash it using the p variant target in avrdude). However, using your 88 makefile changing the target to the 88p did work. So, I guess it was either something else that changed between makefiles (168 and 88) or I did something very different, which I doubt. I'll test it again when I have the chance.

**Comment by andrebrait** [comment]
Ok, here's what I found out:

Compiling for the Atmega88 indeed works for the Atmega88p, using your makefile.
For some reason, however, I can't change the USB_CFG_DEVICE_NAME and USB_CFG_DEVICE_NAME_LEN parameters, which would be nice because I have two controller ports in a hub and it would be cool to distinguish them. I have tried many things but I always end up with the same description. I don't know if it has to do with Windows. I'll check it later by uninstalling the devices.
Anyway, compiling for the Atmega8 is generating a warning. I think I may have to start a Linux Virtual Machine if I don't get to compile it under Windows.

**Comment by andrebrait** [comment]
Ok, the name can only be different if the Device ID and Vendor ID pair is not the same. I changed the device IDs. I'm not going to redistribute it, so I hope it's ok to do this. If not, please tell me and I'll revert/find another solution ASAP.

As for the warning, it doesn't happen in newer versions of avr-gcc. I guess WinAVR ships a very, very old version.
